apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgrest
  namespace: desafio-kubernetes
spec:
  replicas: 2
  selector:
    matchLabels:
      app: postgrest
  template:
    metadata:
      labels:
        app: postgrest
    spec:
      containers:
        - name: postgrest
          image: postgrest/postgrest:v14.1

          ports:
            - containerPort: 3000
              protocol: TCP

          env:
            - name: PGRST_DB_URI
              value: "postgres://app_user@postgres-service:5432/app_db"

            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD

            - name: PGRST_DB_ANON_ROLE
              valueFrom:
                configMapKeyRef:
                  name: postgrest-config
                  key: PGRST_DB_ANON_ROLE

            - name: PGRST_DB_SCHEMAS
              valueFrom:
                configMapKeyRef:
                  name: postgrest-config
                  key: PGRST_DB_SCHEMAS

            - name: PGRST_SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: postgrest-config
                  key: PGRST_SERVER_PORT

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
            timeoutSeconds: 2
            failureThreshold: 3
